dashboard/config/routes.rb
Rails.application.routes.draw do
  get 'students/index'

  get '/dojos/:id/students/new', to: 'students#new', as: 'students_new'

  post '/dojos/:id/students' => 'students#create' 

  get '/dojos/:id/students/:s_id', to: 'students#show', as: 'students_show'

  get '/dojos/:id/students/:s_id/edit', to: 'students#edit', as: 'students_edit' 

  patch '/dojos/:id/students/:s_id' => 'students#update'

  delete '/dojos/:id/students/:s_id' => 'students#destroy'

  get '/dojos' => 'dojos#index'

  get '/dojos/new' => 'dojos#new'

  post '/dojos' => 'dojos#create'

  get '/dojos/:id', to: 'dojos#show', as: 'dojos_show'

  get '/dojos/:id/edit' => 'dojos#edit'

  patch '/dojos/:id' => 'dojos#update'

  delete '/dojos/:id' => 'dojos#destroy'
   

end

dashboard/app/models/dojo.rb
class Dojo < ActiveRecord::Base
	has_many :students
	validates :branch, :street, :city, :state, presence: true
end

dashboard/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :dojo

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, :email, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }

  def self.with_dojo student_id
    self.joins(:dojo).where("students.id = ?", student_id).select(:id, :first_name, :last_name, :email, :branch, :dojo_id, :created_at).first
  end

  def self.cohort student
    self.where("id != ? AND dojo_id = ? AND DATE(created_at) = ?", student.id, student.dojo_id, student.created_at.strftime("%Y-%m-%d"))
  end

end

dashboard/app/controllers/dojos_controller.rb
class DojosController < ApplicationController
	def index
		@dojos = Dojo.all
	end

	def show
		@dojo = Dojo.find(params[:id])
		@students = Dojo.find(params[:id]).students.all
	end

	def new
		@dojo = Dojo.new
	end

	def create
		@dojo = Dojo.new(dojo_params)

		if @dojo.save
			redirect_to dojos_path(@dojo), notice: "You have successfully created a Dojo!"
		else
     	    flash[:errors] = @dojo.errors.full_messages
			redirect_to dojos_new_path
		end
	end

    def edit
		@dojo = Dojo.find(params[:id])
    end

    def update
    	@dojo = Dojo.find(params[:id])
    	@dojo.branch = params[:branch]
    	@dojo.street = params[:street]
    	@dojo.city = params[:city]
    	@dojo.state = params[:state]
		if @dojo.save
			redirect_to dojos_path(@dojo), notice: "You have successfully updated a Dojo!"
		else
     	    flash[:errors] = @dojo.errors.full_messages
			redirect_to dojos_new_path
		end

    end

    def destroy
    	dojo = Dojo.find(params[:id])
    	dojo.destroy
		redirect_to dojos_path
	end

	private
	def dojo_params
		params.require(:dojo).permit(:branch, :street, :city, :state)
	end

end

dashboard/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  end

  def new
    @dojos = Dojo.all
    @dojo = Dojo.find(params[:id])
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to "/dojos/#{@student.dojo_id}", notice: "You have successfully created a Student!"
    else
      flash[:errors] = @student.errors.full_messages
      redirect_to :back
    end
  end

  def show
    @student = Student.with_dojo(params[:s_id])
    @cohort = Student.cohort(@student)
  end

  def edit
    @dojos = Dojo.all
    @student = Student.find(params[:s_id])
  end

  def update
    @student = Student.find(params[:s_id])

    if @student.update(student_params)
      redirect_to students_show_path(@student.dojo_id, @student), notice: "You have successfully updated a Student!"
    else
      flash[:errors] = @student.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
    Student.find(params[:s_id])
    redirect_to :root
  end

  private
  def student_params
    params.require(:student).permit(:first_name, :last_name, :email, :dojo_id)
  end
end

dashboard/app/helpers/application_helper.rb
module ApplicationHelper
  def my_link_to(text, href)
    "<a href='#{href}'>#{text}</a>".html_safe
  end
end

dashboard/app/helpers/students_helper.rb
module StudentsHelper
end

dashboard/app/views/dojos/edit.html.erb
<div class="panel-heading">

    <h3>Editing <%= @dojo.branch %></h3>	

	<% if flash[:errors] %>
		<% flash[:errors].each do |e| %>
			<p><%= e %></p>
		<% end %>
	<% end %>

	<form action="/dojos/<%= @dojo.id %>" method='post'>
		<input type="hidden" name="_method" value="patch">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<p>
			<label>Branch:</label>
			<input type="text" name="branch" value="<%= @dojo.branch %>">
		</p>
		<p>
			<label>Street:</label>
			<input type="text" name="street" value="<%= @dojo.street %>">
		</p>
		<p>
			<label>City:</label>
			<input type="text" name="city" value="<%= @dojo.city %>">
        </p>
        <p>
        	<label>State:</label>
			<input type="text" name="state" value="<%= @dojo.state %>">
		</p>
		<button type="submit" class="btn btn-default">Update Dojo</button>		
	</form>
	<a href="/dojos">Home</a>
</div>

dashboard/app/views/dojos/index.html.erb
<h1>List all Dojos</h1>

<table class="table table-bordered table-striped">
<thead>
	<tr>
		<th>Coding Dojo Branch</th>
		<th>Street</th>
		<th>City</th>
		<th>State</th>
		<th>Actions</th>
	</tr>
</thead>
<tbody>

	<% @dojos.each do |dojo| %>
		<tr>
			<td><%= dojo.branch %></td>
			<td><%= dojo.street %></td>
			<td><%= dojo.city %></td>
			<td><%= dojo.state %></td>
			<td><a href="/dojos/<%= dojo.id %>">Show</a>
			    <a href="/dojos/<%= dojo.id %>/edit">Edit</a>
			    <a href="/dojos/<%= dojo.id %>">Destroy</a></td>
		</tr>
	<% end%>
</table>
<td><a href="dojos/new">New Dojo</a></td>

dashboard/app/views/dojos/new.html.erb
<div class="col-lg-12">  

    <h3>Creating a New Dojo</h3>

	<% if flash[:errors] %>
		<% flash[:errors].each do |e| %>
			<p><%= e %></p>
		<% end %>
	<% end %>

	<div class="panel-heading"> 
	<%= form_for(@dojo) do |d| %>

	<div class="form-group">
		<%= d.label :branch %>
		<%= d.text_field :branch %>
	
		<%= d.label :street %>
		<%= d.text_field :street %>

		<%= d.label :city %>
		<%= d.text_field :city %>

		<%= d.label :state %>
		<%= d.text_field :state %>
		<button type="submit" class="btn btn-default">Create</button>
	</div>

	<% end %>
	<a href="/dojos">Home</a>
</div>

dashboard/app/views/dojos/show.html.erb
<div class="panel-heading">

    <h3>Dojo <%= @dojo.branch %></h3>	

	<form action="/dojos/<%= @dojo.id %>" method='post'>
		<input type="hidden" name="_method" value="delete">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<input type="text" name="branch" value="<%= @dojo.branch %>">
		<input type="text" name="street" value="<%= @dojo.street %>">
		<input type="text" name="city" value="<%= @dojo.city %>">
		<input type="text" name="state" value="<%= @dojo.state %>">
		<button type="submit" class="btn btn-default">Destroy Dojo</button>		
	</form>
	<a href="/dojos/<%= @dojo.id %>/edit">Edit</a>


	<h4>Student Roster</h4>
	<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>

		<% @students.each do |student| %>
			<tr>
				<td><%= student.first_name %></td>
				<td><%= student.last_name %></td>
				<td><%= student.email %></td>
				<td><a href="/dojos/<%= @dojo.id %>/students/<%= student.id %>">Show</a>
				    <%= my_link_to "Edit", students_edit_path(@dojo.id, student.id) %>
				    <a href="/dojos/<%= @dojo.id %>/students/<%= student.id %>">Destroy</a></td>
			</tr>
		<% end%>
	</table>
	<%= my_link_to "Home", dojos_path %> | <%= my_link_to "Add Student", students_new_path(@dojo.id) %>

</div>

dashboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

dashboard/app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

dashboard/app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

dashboard/app/views/students/edit.html.erb
<h1>Edit <%= "#{@student.first_name} #{@student.last_name}" %></h1>

<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<% end %>
<% end %>	

<form action="/dojos/<%= @student.dojo_id %>/students/<%= @student.id %>" method="post">
	<input type="hidden" name="_method" value="patch">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<p>
		<label>First Name:</label>
		<input type="text" name=student[first_name] value="<%= @student.first_name %>">
	</p>
	<p>
		<label>Last Name:</label>
		<input type="text" name="student[last_name]" value="<%= @student.last_name %>">
	</p>
	<p>
		<label>Email:</label>
		<input type="text" name=student[email] value="<%= @student.email %>">
	</p>
	<p>
		<label>Dojo:</label>
		<select name="student[dojo_id]">
			<% @dojos.each do |dojo| %>
				<% if dojo.id == @student.dojo_id %>
					<option selected value="<%= dojo.id %>"><%= dojo.branch %></option>
				<% else %>
					<option value="<%= dojo.id %>"><%= dojo.branch %></option>
				<% end %>
			<% end %>	
		</select>
	</p>
	<button type="submit" class="btn btn-default">Update</button>
</form>


<%= my_link_to "Home", dojos_path %> | <%= my_link_to "#{@student.first_name}", students_show_path(@student.dojo_id, @student) %>

dashboard/app/views/students/index.html.erb
<h1>Students#index</h1>
<p>Find me in app/views/students/index.html.erb</p>

dashboard/app/views/students/new.html.erb
<div class="col-lg-12">    

    <h3>Creating a New Student</h3>

	<% if flash[:errors] %>
		<% flash[:errors].each do |e| %>
			<p><%= e %></p>
		<% end %>
	<% end %>
	
	<div class="panel-heading"> 

		<form action="/dojos/<%= @dojo.id %>/students" method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<p>
				<label>First Name:</label>
				<input type="text" name=student[first_name]>
			</p>
			<p>
				<label>Last Name:</label>
				<input type="text" name="student[last_name]">
			</p>
			<p>
				<label>Email:</label>
				<input type="text" name=student[email]>
			</p>
			<p>
				<label>Dojo:</label>
				<select name="student[dojo_id]">
					<% @dojos.each do |dojo| %>
						<% if dojo == @dojo %>
							<option selected value="<%= dojo.id %>"><%= dojo.branch %></option>
						<% else %>
							<option value="<%= dojo.id %>"><%= dojo.branch %></option>
						<% end %>
					<% end %>	
				</select>
			</p>

			<button type="submit" class="btn btn-default">Create</button>

		</form>
	</div>
	
	<%= my_link_to "Home", dojos_path %> | <%= my_link_to "#{@dojo.branch}", dojos_show_path(@dojo.id) %>

</div>

dashboard/app/views/students/show.html.erb
<div class="panel-heading">

	<h3><%= "#{@student.branch}'s #{@student.first_name} #{@student.last_name}" %></h3>

	<h4>Email: <%= "#{@student.email}" %></h4>

	<h4>Cohort</h4>

	<table class="table table-bordered table-striped">
		<thead>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
		</thead>
		<tbody>
			<% @cohort.each do |student| %>
			<tr>
				<td><%= student.first_name %></td>
				<td><%= student.last_name %></td>
				<td><%= student.email %></td>
			</tr>
			<% end %>
		</tbody>
	</table>


<%= my_link_to "Home", dojos_path %>  | <%= my_link_to "Edit", students_edit_path(@student.dojo_id, @student.id) %>

dashboard/app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>