layouts_assignment/config/routes.rb
Rails.application.routes.draw do
  get 'posts/index' => 'posts#index'

  get 'users/index' => 'users#index'

end

layouts_assignment/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  validates :title, :content, presence: true
end

layouts_assignment/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  validates :first_name, :last_name, :favorite_language, presence: true
end

layouts_assignment/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user)
    @users = User.all
    render layout: "three_columns"
  end

  def create
    @post = Post.new(posts_params)

    if @post.save
      redirect_to posts_path
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to :back
    end
  end

  private
    def posts_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

layouts_assignment/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render layout: "two_columns"
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to :back
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :favorite_language)
    end
end

layouts_assignment/app/helpers/posts_helper.rb
module PostsHelper
end

layouts_assignment/app/helpers/users_helper.rb
module UsersHelper
end

layouts_assignment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LayoutsAssignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

layouts_assignment/app/views/layouts/three_columns.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Three Columns Layout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <%= yield :left_column %> 
      </div>
      
      <div class="col-md-4">
        <%= yield :middle_column %>      
      </div>
      <div class="col-md-4">
        <%= yield :right_column %>
      </div>
    </div>
  </div>

<%= yield %>

</body>
</html>

layouts_assignment/app/views/layouts/two_columns.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Two Columns Layout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <%= yield :left_column %>
      </div>
      <div class="col-md-6">
        <%= yield :right_column %>
      </div>
    </div>
  </div>

<%= yield %>

</body>
</html>

layouts_assignment/app/views/posts/index.html.erb
<% content_for :left_column do %>
  <h1>All Posts</h1>
  <table class="table table-striped">
    <thead>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= "#{post.user.first_name} #{post.user.last_name}" %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<% content_for :middle_column do %>
  <h1>New Post</h1>

  <% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
      <p class="alert alert-danger"><%= e %></p>
    <% end %>
  <% end %>
    
  <form action="/posts" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" class="form-control" id="title" name="post[title]">
    </div>
    <div class="form-group">
      <label for="content">Content</label>
       <textarea class="form-control" rows="5" id="content" name="post[content]"></textarea>
    </div>
    <div class="form-group">
      <label for="author">Author</label>
      <select id="author" name="post[user_id]">
        <% @users.each do |u| %>
          <option value="<%= u.id %>"><%= "#{u.first_name} #{u.last_name}" %></option>  
        <% end %>
      </select>
    </div>
    <input type="submit" class="btn btn-primary" name="Create Post">
  </form>
<% end %>

<% content_for :right_column do %>
  <h2>Go to Users Page</h2>
  <p><%= link_to "All Users", users_index_path, class: "btn btn-info" %></p>
<% end %>

layouts_assignment/app/views/users/index.html.erb
<% content_for :left_column do %>
	<h1>All Users</h1>
	<table class="table table-striped">
		<thead>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Favorite Language</th>
		</thead>
		<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.first_name %></td>
				<td><%= user.last_name %></td>
				<td><%= user.favorite_language %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
<% end %>

<% content_for :right_column do %>
	<h1>New User</h1>

	<% if flash[:errors] %>
		<% flash[:errors].each do |e| %>
			<p class="alert alert-danger"><%= e %></p>
		<% end %>
	<% end %>
		
	<form action="/users" method="post">
    	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    	<div class="form-group">
      		<label for="first_name">First name</label>
      		<input type="text" class="form-control" id="first_name" name="user[first_name]">
    	</div>
    	<div class="form-group">
      		<label for="last_name">Last name</label>
      		<input type="text" class="form-control" id="last_name" name="user[last_name]">
    	</div>
    	<div class="form-group">
      		<label for="favorite_language">Favorite Language</label>
      		<input type="text" class="form-control" id="favorite_language" name="user[favorite_language]">
    	</div>
    	<input type="submit" class="btn btn-primary" name="Create User">
	</form><br>


	<p><%= link_to "All Posts", posts_index_path, class: "btn btn-info" %></p>

<% end %>